### ISSUE TITLE
TinyTeX fails to install on older distros

### ISSUE THREAD

**Issue by glin** [rstudio/r-docker#66]
Builds for older distros like Ubuntu 16, CentOS 7, and openSUSE 42 currently fail on the TinyTeX installation: https://app.circleci.com/pipelines/github/rstudio/r-docker/375/workflows/88494032-53f9-4406-b5d7-d48e7b71b504/jobs/2750

There's an issue for this at https://github.com/yihui/tinytex/issues/280, so we'll just monitor that for a while.

**Comment by cderv** [comment]
@glin this is now fixed and should work as expected.

**Comment by glin** [comment]
@cderv Awesome, thanks! I'll retest and close this.

**Comment by glin** [comment]
@cderv The TinyTeX installations still fail, I think because we're still using the source install script (https://yihui.org/tinytex/install-unx.sh). Do you know if source installations are still supported? I just noticed it's not mentioned in the docs anymore, so maybe not. But if not, that's no problem since the binary installation looks much nicer, and we can switch to that instead.

The source install script itself downloads fine, but it fails when running `wget` on two other URLs that return 308s:
```sh
$ wget https://yihui.org/gh/tinytex/tools/install-base.sh 
--2021-02-18 22:09:03--  https://yihui.org/gh/tinytex/tools/install-base.sh
Resolving yihui.org (yihui.org)... 76.76.21.21
Connecting to yihui.org (yihui.org)|76.76.21.21|:443... connected.
HTTP request sent, awaiting response... 308 Permanent Redirect
2021-02-18 22:09:04 ERROR 308: Permanent Redirect.

$ wget https://yihui.org/gh/tinytex/tools/pkgs-custom.txt
--2021-02-18 22:09:12--  https://yihui.org/gh/tinytex/tools/pkgs-custom.txt
Resolving yihui.org (yihui.org)... 76.76.21.21
Connecting to yihui.org (yihui.org)|76.76.21.21|:443... connected.
HTTP request sent, awaiting response... 308 Permanent Redirect
2021-02-18 22:09:13 ERROR 308: Permanent Redirect.
```

**Comment by cderv** [comment]
Oh yes I assumed you were using the Github action which is using the binary install. 

The issue is with old version of `wget` not supporting the 308 as redirect. This cause error on Ubuntu 16.04 (not 18 or 20). So the status code was changed to 301 but not for this specific url https://yihui.org/gh/

We now indeed recommend the binary installation (https://yihui.org/tinytex/#installation). They are built monthly in https://github.com/yihui/tinytex-releases and available in 3 flavors. One advantage is that they are tested against some R document to include relevant TeX packages to work with Rmarkdown. It could also be quicker to install on Linux. 

DO you think you'll switch ? 

I reported the 308 still there to Yihui

**Comment by cderv** [comment]
@glin FYI the change was also made for this url now. So it should work in your current setup. I let you check

**Comment by glin** [comment]
@cderv Confirmed that the source install works now, thanks! And yes, I'd like to switch over to the binary installation. Those are all great reasons to switch.
